camunda:
    bpm:
      admin-user:
        id: ${CAMUNDA_USR}
        password: ${CAMUNDA_PASS}
spring:
  datasource:
    username: ${CAMUNDA_DS_USR}
    url: ${CAMUNDA_URL}
    password: ${CAMUNDA_DS_PASS}
    driver-class-name: org.postgresql.Driver
book:
  api:
    url: ${BOOK_API_URL}
feign:
  client:
    config:
      postFeignClient:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
        decode404: false