version: "3"
services:
  
  localstack:
    container_name: aws_sqs
    hostname: ${HOSTNAME_EXTERNAL}
    image: localstack/localstack:latest
    command: /bin/sh -c "aws --endpoint-url=http://localhost:4566 sqs create-queue --queue-name elbow.fifo --attributes FifoQueue=true"
    environment:
      - AWS_REGION=${AWS_REGION}
      - EDGE_PORT=4566
      - SERVICES=sqs
      - HOSTNAME_EXTERNAL=${HOSTNAME_EXTERNAL}
      - LOCALSTACK_HOSTNAME=${HOSTNAME_EXTERNAL}
    ports:
      - '4566:4566'
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
  
  database:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=${DS_NAME}
      - MYSQL_ROOT_PASSWORD=${DS_PASS}
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  producer:
    container_name: elbow-producer
    build:
      context: ./producer/
      dockerfile: ./Dockerfile
    image: elbow-producer:latest
    ports:
      - '8082:8082'
    environment:
      - QUEUE_URL=${QUEUE_PROVIDER}:4566/${QUEUE_ACCOUNT}/${QUEUE_NAME}
      - DS_URL=${DS_PROVIDER}:3306/${DS_NAME}
      - DS_PASS=${DS_PASS}
      - DS_USR=${DS_USR}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_OUTPUT=${AWS_DEFAULT_OUTPUT}
  
  consumer:
    container_name: elbow-consumer
    build:
      context: ./consumer/
      dockerfile: ./Dockerfile
    image: elbow-consumer:latest
    ports:
      - '8081:8081'
    environment:
      - QUEUE_URL=${QUEUE_PROVIDER}:4566/${QUEUE_ACCOUNT}/${QUEUE_NAME}
      - DS_URL=${DS_PROVIDER}:3306/${DS_NAME}
      - DS_PASS=${DS_PASS}
      - DS_USR=${DS_USR}
      - AWS_REGION=${AWS_REGION}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_OUTPUT=${AWS_DEFAULT_OUTPUT}
    links:
      - database
      - localstack
    depends_on:
      - database
      - localstack
    volumes:
      - chmod +x ./sqs_bootstrap.sh
  
  databace:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DS_USR_CE}
      POSTGRES_PASSWORD: ${DS_PASS_CE}
      POSTGRES_DB: ${DS_NAME_CE}
    volumes:
      - ./db-data/:/var/lib/postgresql/data/
  
  camunda:
    container_name: camunda-engine-elbow
    build:
      context: ./camunda-engine/
      dockerfile: ./Dockerfile
    image: camunda-engine-elbow:latest
    ports:
      - '8080:8080'
    environment:
      - DS_URL_CE=${DS_PROVIDER_CE}:${DS_PORT_CE}/${DS_NAME_CE}
      - DS_PASS_CE=${DS_PASS_CE}
      - DS_USR_CE=${DS_USR_CE}
      - USR_CE=${USR_CE}
      - PASS_CE=${PASS_CE}
      - BOOK_API_URL=${BOOK_API_URL}
    depends_on:
      - databace
      - producer
      - localstack
    links:
      - databace
      - producer
volumes:
  db:
    driver: local