---
security:
  auth:
    cookie:
      same-site:
        enabled: true
    token:
      lifeMin: 60
      secret: null
    superUserIds: []

  responseHeaders:
    HSTS:
      max-age: 31536000
      includeSubDomains: true
    X-XSS-Protection: 1; mode=block
    X-Content-Type-Options: true
    Content-Security-Policy: base-uri 'self'

api:
  accessToken: ${OPTIMIZE_API_ACCESS_TOKEN:null}
  jwtSetUri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:null}

container:
  host: localhost
  ports:
    http: 8090
    https: 8091
  keystore:
    location: keystore.jks
    password: optimize
  status:
    connections:
      max: 10
  accessUrl: null

engines:
  'camunda-bpm':
    name: default
    defaultTenant:
      id: null
      name: null
    rest: ${OPTIMIZE_CAMUNDABPM_REST_URL}
    importEnabled: true
    eventImportEnabled: false
    authentication:
      enabled: true
      password: 'sa'
      user: 'root'
    webapps:
      endpoint: ${CAMUNDA_BPMN_URL}
      enabled: true

engine-commons:
  connection:
    timeout: 0
  read:
    timeout: 0

import:
  data:
    activity-instance:
      maxPageSize: 10000
    incident:
      maxPageSize: 10000
    process-definition-xml:
      maxPageSize: 2
    process-definition:
      maxPageSize: 10000
    process-instance:
      maxPageSize: 10000
    variable:
      maxPageSize: 10000
      includeObjectVariableValue: true
    user-task-instance:
      maxPageSize: 10000
    identity-link-log:
      maxPageSize: 10000
    decision-definition-xml:
      maxPageSize: 2
    decision-definition:
      maxPageSize: 10000
    decision-instance:
      maxPageSize: 10000
    tenant:
      maxPageSize: 10000
    group:
      maxPageSize: 10000
    authorization:
      maxPageSize: 10000
    dmn:
      enabled: true
    user-task-worker:
      enabled: true
      metadata:
        includeUserMetaData: true
        cronTrigger: '0 */3 * * *'
        maxPageSize: 10000
        maxEntryLimit: 100000
  skipDataAfterNestedDocLimitReached: false
  elasticsearchJobExecutorThreadCount: 1
  elasticsearchJobExecutorQueueSize: 5
  handler:
    backoff:
      initial: 1000
      max: 30
  importIndexStorageIntervalInSec: 10
  currentTimeBackoffMilliseconds: 300000
  identitySync:
    includeUserMetaData: true
    cronTrigger: '0 */2 * * *'
    maxPageSize: 10000
    maxEntryLimit: 100000

es:
  connection:
    timeout: 10000
    responseConsumerBufferLimitInMb: 100
    pathPrefix: ''
    nodes:
      - host: ${ELASTICSEARCH_HOST}
        httpPort: 9200
    proxy:
      enabled: false
      host: null
      port: null
      sslEnabled: false


  security:
    username: null
    password: null
    ssl:
      certificate: null
      certificate_authorities: []
      enabled: false

  scrollTimeout: 60000
  settings:
    aggregationBucketLimit: 1000
    index:
      prefix: 'optimize'
      number_of_replicas: 1
      number_of_shards: 1
      refresh_interval: 2s
      nested_documents_limit: 10000

plugin:
  directory: './plugin'
  variableImport:
    basePackages: []
  engineRestFilter:
    basePackages: []
  authenticationExtractor:
    basePackages: []
  decisionInputImport:
    basePackages: []
  decisionOutputImport:
    basePackages: []
  elasticsearchCustomHeader:
    basePackages: []

serialization:
  engineDateFormat: yyyy-MM-dd'T'HH:mm:ss.SSSZ

alerting:
  quartz:
    jobStore: 'org.quartz.simpl.RAMJobStore'

email:
  enabled: false
  address: ''
  hostname: ''
  port: 587
  authentication:
    enabled: true
    username: ''
    password: ''
    securityProtocol: 'NONE'

export:
  csv:
    limit: 1000

sharing:
  enabled: true

historyCleanup:
  cronTrigger: '0 1 * * *'
  ttl: 'P2Y'
  processDataCleanup:
    enabled: false
    cleanupMode: 'all'
    batchSize: 10000
    perProcessDefinitionConfig:
  decisionDataCleanup:
    enabled: false
    perDecisionDefinitionConfig:
  ingestedEventCleanup:
    enabled: false

locales:
  availableLocales: ['en', 'de']
  fallbackLocale: 'en'

ui:
  header:
    textColor: 'dark'
    pathToLogoIcon: 'logo/camunda_icon.svg'

eventBasedProcess:
  eventImport:
    enabled: false
    maxPageSize: 5000
  eventIngestion:
    maxBatchRequestBytes: 10485760
    maxRequests: 5
  eventIndexRollover:
    scheduleIntervalInMinutes: 10
    maxIndexSizeGB: 50

externalVariable:
  import:
    enabled: false
    maxPageSize: 10000
  variableIngestion:
    maxBatchRequestBytes: 10485760
    maxRequests: 5
  variableIndexRollover:
    scheduleIntervalInMinutes: 10
    maxIndexSizeGB: 50

telemetry:
  initializeTelemetry: false