server:
  port: 8080
spring:
  datasource:
    url: ${DS_URL}
    username: ${DS_USR}
    password: ${DS_PASS}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
aws:
  url:
    queue: ${QUEUE_URL}