server:
  port: 8080
spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: ${DS_URL}
    username: ${DS_USR}
    password: ${DS_PASS}
aws:
  url:
    queue: ${QUEUE_URL}